import React from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import "./globals.css";
import { Space } from "@/app/components/Space";
import StyledComponentsRegistry from "./lib/registry";
import { SpaceContextProvider } from "../../contexts/useSpace";
import { Web3ContextProvider } from "../../contexts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <Head>
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </Head>
      <body className={inter.className}>
        <Web3ContextProvider>
          <SpaceContextProvider>
            <Space
              style={{
                position: "absolute",
                zIndex: -1,
                height: "100%",
                width: "100%",
              }}
            />
            <StyledComponentsRegistry>
              <div
                style={{
                  height: "100%",
                  width: "100%",
                  padding: "20px",
                  overflowY: "auto",
                }}
              >
                {children}
              </div>
            </StyledComponentsRegistry>
          </SpaceContextProvider>
        </Web3ContextProvider>
      </body>
    </html>
  );
}
